sut:
  build: .
  entrypoint: /bin/sh -c
  command: docker-compose.test.yml.sh
  environment:
    - SOURCE_BRANCH
    - SOURCE_COMMIT
    - COMMIT_MSG
    - DOCKER_REPO
    - DOCKERFILE_PATH
    - DOCKER_TAG
    - IMAGE_NAME
